workspace:
  base: /ceshi/api
  path: .
pipeline:
  init:
    image: node:latest
    commands:
      - npm run test
    when:
      event: [push, tag, deployment]
      branch: [master, develop]
  build:
    image: node:latest
    environment:
      - TZ=Asia/Shanghai
    commands:
      - npm run start
    when:
      event: [push, tag, deployment]
      branch: [master, develop]
